package controller.commands;

import java.util.Scanner;

import model.IMEModel;

/**
 * Represents a command object to change the brightness of an image.
 */
public class ChangeBrightness implements IMECommand {
  private int increment;
  private final String imageName;
  private final String newImageName;

  /**
   * Constructs a new ChangeBrightness command object.
   * @param s the Scanner from which the increment to change the brightness by, the name of the
   *          image to change the brightness of, and the name for the new image generated by
   *          incrementing the brightness of the original image are parsed
   * @param brighten true if brightening, false if darkening
   */
  public ChangeBrightness(Scanner s, boolean brighten) {
    increment = s.nextInt();
    if (! brighten) {
      increment = 0 - increment;
    }
    imageName = s.next();
    newImageName = s.next();
  }

  /**
   * Constructor for a new ChangeBrightness command object that details the amount by which
   * the image brightness should be changed (either positive or negative).
   *
   * @param increment increments the brightness of each of a pixel's components by the specified
   *                  amount, clamped at 0 or 255
   */
  public ChangeBrightness(int increment) {
    this.increment = increment;
    imageName = "";
    newImageName = "";
  }

  @Override
  public void doThing(IMEModel model) throws IllegalArgumentException {
    model.changeBrightness(increment, imageName, newImageName);
  }

  @Override
  public String description() {
    return "Changed brightness of image " + imageName + " by an increment of " + increment
            + " and stored it in the model as " + newImageName + "\n";
  }
}
