package controller.commands;

import java.util.Scanner;

import model.IMEModel;

/**
 * Represents a command object to flip an image horizontally or vertically.
 */
public class Flip implements IMECommand {
  private final String imageName;
  private final String newImageName;
  private final String type;

  /**
   * Constructs a new Flip command object.
   *
   * @param s    the Scanner from which the name of the image to be flipped and the name for the new
   *             image generated by flipping the original image are parsed
   * @param type "horizontal" or "vertical"
   * @throws IllegalArgumentException if type is not "horizontal" or "vertical"
   */
  public Flip(Scanner s, String type) throws IllegalArgumentException {
    imageName = s.next();
    newImageName = s.next();
    if (!type.equals("horizontal") && !type.equals("vertical")) {
      throw new IllegalArgumentException("invalid type provided");
    }
    this.type = type;
  }

  /**
   * Constructs a new Flip command object.
   *
   * @param type "horizontal" or "vertical" flipping operation.
   */
  public Flip(String type) {
    imageName = "";
    newImageName = "";
    if (!type.equals("horizontal") && !type.equals("vertical")) {
      throw new IllegalArgumentException("invalid type provided");
    }
    this.type = type;
  }

  @Override
  public void doThing(IMEModel model) throws IllegalArgumentException {
    model.flip(type, imageName, newImageName);
  }

  @Override
  public String description() {
    return "Flipped image " + imageName + " " + type
            + "ly and stored it in the model as " + newImageName + "\n";
  }
}
